type Category {
  id: String!
  name: String!
  userId: String!
  createdAt: String!
  updatedAt: String!
}

input CreateCategoryInput {
  name: String!
}

input UpdateCategoryInput {
  name: String
}

extend type Query {
  listCategories: [Category!]!
  getCategory(id: String!): Category!
}

extend type Mutation {
  createCategory(data: CreateCategoryInput!): Category!
  updateCategory(id: String!, data: UpdateCategoryInput!): Category!
  deleteCategory(id: String!): Boolean!
}
